# Generated by Django 3.1.6 on 2021-02-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_first', models.TextField(verbose_name='First field')),
            ],
        ),
        migrations.CreateModel(
            name='TableSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_second', models.TextField(verbose_name='Second field')),
                ('table_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.tablefirst')),
            ],
        ),
    ]
